# Generated by Django 4.1.2 on 2022-11-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_participant_subit1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='branch',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='phone',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='roll',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='email',
            new_name='q5',
        ),
    ]
