# Generated by Django 4.1.3 on 2022-11-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_branch_participant_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='q2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q3',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q5',
            field=models.IntegerField(),
        ),
    ]
