# Generated by Django 4.1.3 on 2022-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_participant_q2_alter_participant_q3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='subit',
        ),
        migrations.AddField(
            model_name='participant',
            name='q6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='q7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='q8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='q5',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
